package ru.yandex.javacourse.schedule.manager;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import ru.yandex.javacourse.schedule.tasks.Epic;
import ru.yandex.javacourse.schedule.tasks.Subtask;
import ru.yandex.javacourse.schedule.tasks.Task;
import ru.yandex.javacourse.schedule.tasks.TaskStatus;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

public class InMemoryTaskManagerTest {

    TaskManager manager;

    @BeforeEach
    public void initManager(){
        manager = Managers.getDefault();
    }

    @Test
    public void testAddTask() {
        Task task = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().get(0);
        assertEquals(task, addedTask, "added task id should be set");
        Task byIdTask = manager.getTask(task.getId());
        assertEquals(task, byIdTask, "added task id should be found");
    }

    @Test
    public void testAddTaskWithId(){
        Task task = new Task(42, "Test 1", "Testing task 1", TaskStatus.NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().get(0);
        assertEquals(task, addedTask, "predefined task id should be set");
    }

    @Test
    public void addNewTask_predefinedIdShouldRemain_predefinedTaskWasAddedBeforeUndefinedTask(){
        Task task0 = new Task(2, "Test 1", "Testing task 1", TaskStatus.NEW);
        Task task1 = new Task("Test 2", "Testing task 2", TaskStatus.NEW);
        manager.addNewTask(task0);
        manager.addNewTask(task1);
        assertEquals(2, manager.getTasks().size(), "the same size of tasks in manager");
        assertEquals(2, task0.getId(), "task predefined id should not change");
        assertEquals(1, task1.getId(), "autogenerated id should be 1");
    }

    @Test
    public void addNewTask_predefinedIdShouldChange_predefinedTaskWasAddedAfterUndefinedTask(){
        Task task0 = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
        Task task1 = new Task(1, "Test 2", "Testing task 2", TaskStatus.NEW);
        manager.addNewTask(task0);
        manager.addNewTask(task1);
        assertEquals(2, manager.getTasks().size(), "the same size of tasks in manager");
        assertEquals(1, task0.getId(), "autogenerated id should be 1");
        assertEquals(2, task1.getId(), "predefined task will change id due to the order of addition");
    }

    @Test
    public void checkTaskNotChangedAfterAddTask() {
        int id = 1;
        String name = "Test 1";
        String description = "Testing task 1";
        TaskStatus status = TaskStatus.NEW;
        Task task1before = new Task(id, name, description, status);
        manager.addNewTask(task1before);
        Task task1after = manager.getTask(task1before.getId());
        assertEquals(task1after.getId(), id);
        assertEquals(task1after.getDescription(), description);
        assertEquals(task1after.getStatus(), status);
        assertEquals(task1after.getName(), name);
    }

    @Test
    public void addNewTask_updateTaskId_newTaskWithSetId() {
        Task task0 = new Task(1, "Test 1", "Testing task 1", TaskStatus.NEW);
        Task task1 = new Task(1, "Test 2", "Testing task 2", TaskStatus.NEW);

        manager.addNewTask(task0);
        manager.addNewTask(task1);

        assertNotEquals(task0.getId(), task1.getId(), "ids should be unequal");
    }

    @Test
    public void addNewTask_createNewTaskWithNewId_newTaskHasIdExistInManager() {
        Task task0 = new Task(1, "Test 1", "Testing task 1", TaskStatus.NEW);
        Task task1 = new Task("Test 2", "Testing task 2 with no set id", TaskStatus.NEW);

        manager.addNewTask(task0);
        manager.addNewTask(task1);

        assertNotEquals(task0.getId(), task1.getId(), "ids should be unequal");
    }

    @Test
    public void addNewSubtask_updateSubtaskId_newSubtaskWithSetId() {
        Epic e0 = new Epic(3, "Test 1", "Testing epic for subtasks");
        manager.addNewEpic(e0);

        Subtask s0 = new Subtask(1, "Test 1", "Testing subtask 1", TaskStatus.NEW, e0.getId());
        Subtask s1 = new Subtask(1, "Test 2", "Testing subtask 2", TaskStatus.NEW, e0.getId());
        manager.addNewSubtask(s0);
        manager.addNewSubtask(s1);

        assertNotEquals(s0.getId(), s1.getId(), "ids should be unequal");
    }

    @Test
    public void addNewSubtask_createNewSubtaskWithNewId_newSubtaskHasIdExistInManager() {
        Epic e0 = new Epic(3, "Test 1", "Testing epic for subtasks");
        manager.addNewEpic(e0);

        Subtask s0 = new Subtask(1, "Test 1", "Testing task 1", TaskStatus.NEW, 3);
        Subtask s1 = new Subtask("Test 2", "Testing task 2", TaskStatus.IN_PROGRESS, 3);

        manager.addNewSubtask(s0);
        manager.addNewSubtask(s1);

        assertNotEquals(s0.getId(), s1.getId(), "ids should be unequal");
    }

    @Test
    public void addNewEpic_updateEpicId_newEpicWithSetId() {
        Epic e0 = new Epic(1, "Test 1", "Testing task 1");
        Epic e1 = new Epic(1, "Test 2", "Testing task 2");

        manager.addNewEpic(e0);
        manager.addNewEpic(e1);

        assertNotEquals(e0.getId(), e1.getId(), "ids should be unequal");
    }

    @Test
    public void addNewEpic_createNewEpicWithNewId_newEpicHasIdExistInManager() {
        Epic e0 = new Epic(1, "Test 1", "Testing task 1");
        Epic e1 = new Epic("Test 2", "Testing task 2");

        manager.addNewEpic(e0);
        manager.addNewEpic(e1);

        assertNotEquals(e0.getId(), e1.getId(), "ids should be unequal");
    }

    @Test
    public void loadFromFile_shouldRestoreTasksEpicsAndSubtasks() throws IOException {
        File source = File.createTempFile("autosave-load", ".txt");
        source.deleteOnExit();
        String fileContent = String.join("\r\n",
                "id,type,name,status,description,epic",
                "7,TASK,Persisted task,NEW,Task description,",
                "8,EPIC,Persisted epic,NEW,Epic description,",
                "9,SUBTASK,Persisted subtask,DONE,Sub description,8"
        );
        Files.writeString(source.toPath(), fileContent);

        manager.loadFromFile(source);

        assertEquals(1, manager.getTasks().size(), "Должна загрузиться одна задача");
        assertEquals(1, manager.getEpics().size(), "Должен загрузиться один эпик");
        assertEquals(1, manager.getSubtasks().size(), "Должна загрузиться одна подзадача");

        Task loadedTask = manager.getTask(7);
        Epic loadedEpic = manager.getEpic(8);
        Subtask loadedSubtask = manager.getSubtask(9);

        assertEquals("Persisted task", loadedTask.getName(), "Имя задачи должно совпадать");
        assertEquals("Persisted epic", loadedEpic.getName(), "Имя эпика должно совпадать");
        assertEquals("Persisted subtask", loadedSubtask.getName(), "Имя подзадачи должно совпадать");
        assertEquals(loadedEpic.getId(), loadedSubtask.getEpicId(), "Связь подзадачи с эпиком должна сохраниться");
    }
}
